FROM  maxtnt/docker_elixir_alpine:v1

# Install dep

# Now copy all the source
RUN mix local.hex --force
RUN mix local.rebar --force
RUN mix archive.install https://github.com/phoenixframework/archives/raw/master/phoenix_new.ez --force

# Install deps
RUN mkdir /app
ADD solvit/mix.exs /app
ADD solvit/mix.lock /app
RUN set -ex ; \
    cd /app ; \
    mix deps.get;

CMD ["/bin/bash"]