version: '3.7'
services:
  solvit:
    image: solvit:base
    env_file:
      - ../env/solvit.env
    container_name: solvit_container
    networks:
      back_net:
          ipv4_address: 192.168.10.2
    volumes:
      - "./volume/solvit:/external_volume"
    working_dir: /workspace
    expose:
     - "80"
     - "443"
    command: bash -c " make init && /bin/bash"
  postgres:
    image: postgres
    restart: always
    networks:
      back_net:
          ipv4_address: 192.168.10.4
    volumes:
    - db_data:/var/lib/postgresql/data
  graphql-engine:
    image: hasura/graphql-engine:v1.0.0-beta.9
    networks:
      back_net:
          ipv4_address: 192.168.10.3
    ports:
    - "8080:8080"
    depends_on:
    - "postgres"
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:@postgres:5432/postgres
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # set to "false" to disable console
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log

networks:
  back_net:
    driver: bridge
    ipam:
      driver: default
      config:
          - subnet: 192.168.10.0/24
volumes: 
  db_data:
    external: true
