version: '3.7'
services:
  solvit:
    image: elixir
    env_file:
      - solvit.env
    networks:
      back_net:
          ipv4_address: 192.168.10.2
    volumes:
      - "./solvit:/workspace"
    working_dir: /workspace
    expose:
     - "80"
     - "443"
    command: bash
  front:
    image: nginx
    depends_on:
    - mongodb
    - cache
    volumes:
      - "./front:/workspace"
    working_dir: /workspace
    networks:
      host:
          ipv4_address: 192.168.1.10
      back_net:
          ipv4_address: 192.168.10.4
  cache:
    image: redis
    networks:
      back_net:
          ipv4_address: 192.168.10.5
  mongodb:
    image: mongo
    networks:
      back_net:
          ipv4_address: 192.168.10.3
networks:
  host:
    external: true
  back_net:
    driver: bridge
    ipam:
      driver: default
      config:
          - subnet: 192.168.10.0/24
